import { Hono } from 'jsr:@hono/hono';
import classesRoutes from './classes.ts';
import subclassesRoutes from './subclasses.ts';
import backgroundsRoutes from './background.ts';
import racesRoutes from './races.ts';
import subracesRoutes from './subraces.ts';
import aiRoutes from './ai.ts';
import abilityscoresRoutes from './abilityscores.ts';
import alignmentsRoutes from './alignments.ts';
import conditionsRoutes from './conditions.ts';
import damagetypesRoutes from './damagetypes.ts';
import equipmentRoutes from './equipment.ts';
import featuresRoutes from './features.ts';
import languagesRoutes from './languages.ts';
import magicitemsRoutes from './magicitems.ts';
import proficienciesRoutes from './proficiencies.ts';
import skillsRoutes from './skills.ts';
import spellsRoutes from './spells.ts';
import traitsRoutes from './traits.ts';
import weaponmasterypropertiesRoutes from './weaponmasteryproperties.ts';
import weaponpropertiesRoutes from './weaponproperties.ts';

const app = new Hono();

app.route('/classes', classesRoutes);
app.route('/subclasses', subclassesRoutes);
app.route('/backgrounds', backgroundsRoutes);
app.route('/races', racesRoutes);
app.route('/subraces', subracesRoutes);
app.route('/ai', aiRoutes);
app.route('/abilityscores', abilityscoresRoutes);
app.route('/alignments', alignmentsRoutes);
app.route('/conditions', conditionsRoutes);
app.route('/damagetypes', damagetypesRoutes);
app.route('/equipment', equipmentRoutes);
app.route('/features', featuresRoutes);
app.route('/languages', languagesRoutes);
app.route('/magicitems', magicitemsRoutes);
app.route('/proficiencies', proficienciesRoutes);
app.route('/skills', skillsRoutes);
app.route('/spells', spellsRoutes);
app.route('/traits', traitsRoutes);
app.route('/weaponmasteryproperties', weaponmasterypropertiesRoutes);
app.route('/weaponproperties', weaponpropertiesRoutes);

export default app;
