import type { CharacterSheet } from '@types';

export const blankCharacter: CharacterSheet = {
  characterName: '',
  playerName: '',
  alignment: '',
  class: '',
  background: '',
  exp: 0,
  age: 0,
  race: '',
  level: 1,
  skills: [],
  inventory: [],
  attributes: {
    strength: 10,
    dexterity: 10,
    intelligence: 10,
    constitution: 10,
    charisma: 10,
    wisdom: 10,
  },
  armorClass: 0,
  initiative: 0,
  speed: 0,
  hitPoints: {
    current: 0,
    maximum: 0,
    temporary: 0,
  },
  hitDice: { die: 6, count: 1, used: 0 },
  savingThrows: [],
  featuresAndTraits: [],
  proficiencies: [],
  languages: [],
  personalityTraits: '',
  ideals: '',
  bonds: '',
  flaws: '',
};
